modLoader="javafml"
loaderVersion="${loader_version_range}"
license="ARR"

[[mods]]
modId="syals_delight"

# The version number of the mod
version="${mod_version}"
displayName="${mod_name}"

authors="y271727uy" #optional


description='''${mod_description}'''


[[dependencies.syals_delight]] #optional
    # the modid of the dependency
    modId="neoforge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="${forge_version_range}"
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT, or SERVER
    side="BOTH"

# Here's another dependency
[[dependencies.syals_delight]]
    modId="minecraft"
    mandatory=true
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"



